### ISSUE TITLE
V2::BankEntriesController#index (ActionView::Template::Error) "undefined method `/' for nil:NilClass"

### ISSUE THREAD

**Issue by DouglasMeyer** [DouglasMeyer/ledger#1]
<table><tr><th>Exception</th><td>undefined method `/&#39; for nil:NilClass</td></tr><tr><th>Last Occurrence</th><td>January 01, 2015 21:05:45 -0600</td></tr><tr><th>Count</th><td>3</td></tr></table>

## Stack Trace
<pre><a href='https://github.com/DouglasMeyer/ledger/blob/b080bc2369b2337baf9d2a90878104928de9453d/lib/dollarify.rb#L6'>[app].../lib/dollarify.rb:6:in `block in dollarify'</a>
[bundle].../gems/actionview-4.1.6/lib/action_view/helpers/tags/base.rb:28:in `value'
[bundle].../gems/actionview-4.1.6/lib/action_view/helpers/tags/base.rb:37:in `value_before_type_cast'
[bundle].../gems/actionview-4.1.6/lib/action_view/helpers/tags/text_field.rb:9:in `block in render'
[bundle].../gems/actionview-4.1.6/lib/action_view/helpers/tags/text_field.rb:9:in `fetch'
[bundle].../gems/actionview-4.1.6/lib/action_view/helpers/tags/text_field.rb:9:in `render'
[bundle].../gems/actionview-4.1.6/lib/action_view/helpers/form_helper.rb:771:in `text_field'
[bundle].../gems/actionview-4.1.6/lib/action_view/helpers/form_helper.rb:1258:in `text_field'
<a href='https://github.com/DouglasMeyer/ledger/blob/b080bc2369b2337baf9d2a90878104928de9453d/app/views/v2/bank_entries/_bank_entry.html.haml#L20'>[app].../app/views/v2/bank_entries/_bank_entry.html.haml:20:in `block (2 levels) in _app_views_v__bank_entries__bank_entry_html_haml__2172996967217411893_70301536344840'</a>
[bundle].../gems/haml-4.0.6/lib/haml/helpers.rb:368:in `call'
[bundle].../gems/haml-4.0.6/lib/haml/helpers.rb:368:in `block in capture_haml'
[bundle].../gems/haml-4.0.6/lib/haml/helpers.rb:608:in `with_haml_buffer'
[bundle].../gems/haml-4.0.6/lib/haml/helpers.rb:364:in `capture_haml'
[bundle].../gems/haml-4.0.6/lib/haml/helpers/xss_mods.rb:61:in `capture_haml_with_haml_xss'
[bundle].../gems/haml-4.0.6/lib/haml/helpers/action_view_mods.rb:45:in `capture_with_haml'
[bundle].../gems/actionview-4.1.6/lib/action_view/helpers/form_helper.rb:1860:in `block in fields_for_nested_model'
[bundle].../gems/actionview-4.1.6/lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
[bundle].../gems/actionview-4.1.6/lib/action_view/helpers/capture_helper.rb:200:in `with_output_buffer'
[bundle].../gems/haml-4.0.6/lib/haml/helpers/action_view_xss_mods.rb:5:in `with_output_buffer_with_haml_xss'
[bundle].../gems/actionview-4.1.6/lib/action_view/helpers/capture_helper.rb:38:in `capture'
[bundle].../gems/haml-4.0.6/lib/haml/helpers/action_view_mods.rb:52:in `capture_with_haml'
[bundle].../gems/actionview-4.1.6/lib/action_view/helpers/form_helper.rb:699:in `fields_for'
[bundle].../gems/actionview-4.1.6/lib/action_view/helpers/form_helper.rb:1859:in `fields_for_nested_model'
[bundle].../gems/actionview-4.1.6/lib/action_view/helpers/form_helper.rb:1845:in `block in fields_for_with_nested_attributes'
[bundle].../gems/activerecord-4.1.6/lib/active_record/relation/delegation.rb:46:in `each'
[bundle].../gems/activerecord-4.1.6/lib/active_record/relation/delegation.rb:46:in `each'
[bundle].../gems/actionview-4.1.6/lib/action_view/helpers/form_helper.rb:1843:in `fields_for_with_nested_attributes'
[bundle].../gems/actionview-4.1.6/lib/action_view/helpers/form_helper.rb:1517:in `fields_for'
<a href='https://github.com/DouglasMeyer/ledger/blob/b080bc2369b2337baf9d2a90878104928de9453d/app/views/v2/bank_entries/_bank_entry.html.haml#L17'>[app].../app/views/v2/bank_entries/_bank_entry.html.haml:17:in `block in _app_views_v__bank_entries__bank_entry_html_haml__2172996967217411893_70301536344840'</a>
[bundle].../gems/haml-4.0.6/lib/haml/helpers/action_view_mods.rb:137:in `call'
[bundle].../gems/haml-4.0.6/lib/haml/helpers/action_view_mods.rb:137:in `block (2 levels) in form_for_with_haml'
[bundle].../gems/haml-4.0.6/lib/haml/helpers.rb:278:in `with_tabs'
[bundle].../gems/haml-4.0.6/lib/haml/helpers/action_view_mods.rb:137:in `block in form_for_with_haml'
[bundle].../gems/actionview-4.1.6/lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
[bundle].../gems/actionview-4.1.6/lib/action_view/helpers/capture_helper.rb:200:in `with_output_buffer'
[bundle].../gems/haml-4.0.6/lib/haml/helpers/action_view_xss_mods.rb:5:in `with_output_buffer_with_haml_xss'
[bundle].../gems/actionview-4.1.6/lib/action_view/helpers/capture_helper.rb:38:in `capture'
[bundle].../gems/haml-4.0.6/lib/haml/helpers/action_view_mods.rb:52:in `capture_with_haml'
[bundle].../gems/actionview-4.1.6/lib/action_view/helpers/form_helper.rb:434:in `form_for'
[bundle].../gems/haml-4.0.6/lib/haml/helpers/action_view_mods.rb:139:in `form_for_with_haml'
[bundle].../gems/haml-4.0.6/lib/haml/helpers/action_view_xss_mods.rb:28:in `form_for_with_haml_xss'
<a href='https://github.com/DouglasMeyer/ledger/blob/b080bc2369b2337baf9d2a90878104928de9453d/app/views/v2/bank_entries/_bank_entry.html.haml#L1'>[app].../app/views/v2/bank_entries/_bank_entry.html.haml:1:in `_app_views_v__bank_entries__bank_entry_html_haml__2172996967217411893_70301536344840'</a>
[bundle].../gems/actionview-4.1.6/lib/action_view/template.rb:145:in `block in render'
[bundle].../gems/activesupport-4.1.6/lib/active_support/notifications.rb:161:in `instrument'
[bundle].../gems/actionview-4.1.6/lib/action_view/template.rb:339:in `instrument'
[bundle].../gems/actionview-4.1.6/lib/action_view/template.rb:143:in `render'
[bundle].../gems/actionview-4.1.6/lib/action_view/renderer/partial_renderer.rb:306:in `render_partial'
[bundle].../gems/actionview-4.1.6/lib/action_view/renderer/partial_renderer.rb:279:in `block in render'
[bundle].../gems/actionview-4.1.6/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
[bundle].../gems/activesupport-4.1.6/lib/active_support/notifications.rb:159:in `block in instrument'
[bundle].../gems/activesupport-4.1.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-4.1.6/lib/active_support/notifications.rb:159:in `instrument'
[bundle].../gems/actionview-4.1.6/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
[bundle].../gems/actionview-4.1.6/lib/action_view/renderer/partial_renderer.rb:278:in `render'
[bundle].../gems/actionview-4.1.6/lib/action_view/renderer/renderer.rb:47:in `render_partial'
[bundle].../gems/actionview-4.1.6/lib/action_view/helpers/rendering_helper.rb:35:in `render'
[bundle].../gems/haml-4.0.6/lib/haml/helpers/action_view_mods.rb:10:in `block in render_with_haml'
[bundle].../gems/haml-4.0.6/lib/haml/helpers.rb:89:in `non_haml'
[bundle].../gems/haml-4.0.6/lib/haml/helpers/action_view_mods.rb:10:in `render_with_haml'
<a href='https://github.com/DouglasMeyer/ledger/blob/b080bc2369b2337baf9d2a90878104928de9453d/app/views/v2/bank_entries/index.html.haml#L5'>[app].../app/views/v2/bank_entries/index.html.haml:5:in `_app_views_v__bank_entries_index_html_haml___3930332536171830022_70301536289700'</a>
[bundle].../gems/actionview-4.1.6/lib/action_view/template.rb:145:in `block in render'
[bundle].../gems/activesupport-4.1.6/lib/active_support/notifications.rb:161:in `instrument'
[bundle].../gems/actionview-4.1.6/lib/action_view/template.rb:339:in `instrument'
[bundle].../gems/actionview-4.1.6/lib/action_view/template.rb:143:in `render'
[bundle].../gems/actionview-4.1.6/lib/action_view/renderer/template_renderer.rb:55:in `block (2 levels) in render_template'
[bundle].../gems/actionview-4.1.6/lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
[bundle].../gems/activesupport-4.1.6/lib/active_support/notifications.rb:159:in `block in instrument'
[bundle].../gems/activesupport-4.1.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-4.1.6/lib/active_support/notifications.rb:159:in `instrument'
[bundle].../gems/actionview-4.1.6/lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
[bundle].../gems/actionview-4.1.6/lib/action_view/renderer/template_renderer.rb:54:in `block in render_template'
[bundle].../gems/actionview-4.1.6/lib/action_view/renderer/template_renderer.rb:62:in `render_with_layout'
[bundle].../gems/actionview-4.1.6/lib/action_view/renderer/template_renderer.rb:53:in `render_template'
[bundle].../gems/actionview-4.1.6/lib/action_view/renderer/template_renderer.rb:17:in `render'
[bundle].../gems/actionview-4.1.6/lib/action_view/renderer/renderer.rb:42:in `render_template'
[bundle].../gems/actionview-4.1.6/lib/action_view/renderer/renderer.rb:23:in `render'
[bundle].../gems/actionview-4.1.6/lib/action_view/rendering.rb:99:in `_render_template'
[bundle].../gems/actionpack-4.1.6/lib/action_controller/metal/streaming.rb:217:in `_render_template'
[bundle].../gems/actionview-4.1.6/lib/action_view/rendering.rb:82:in `render_to_body'
[bundle].../gems/actionpack-4.1.6/lib/action_controller/metal/rendering.rb:32:in `render_to_body'
[bundle].../gems/actionpack-4.1.6/lib/action_controller/metal/renderers.rb:32:in `render_to_body'
[bundle].../gems/actionpack-4.1.6/lib/abstract_controller/rendering.rb:25:in `render'
[bundle].../gems/actionpack-4.1.6/lib/action_controller/metal/rendering.rb:16:in `render'
[bundle].../gems/actionpack-4.1.6/lib/action_controller/metal/instrumentation.rb:41:in `block (2 levels) in render'
[bundle].../gems/activesupport-4.1.6/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/Users/dougmeyer1/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/benchmark.rb:294:in `realtime'
[bundle].../gems/activesupport-4.1.6/lib/active_support/core_ext/benchmark.rb:12:in `ms'
[bundle].../gems/actionpack-4.1.6/lib/action_controller/metal/instrumentation.rb:41:in `block in render'
[bundle].../gems/actionpack-4.1.6/lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
[bundle].../gems/activerecord-4.1.6/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
[bundle].../gems/actionpack-4.1.6/lib/action_controller/metal/instrumentation.rb:40:in `render'
[bundle].../gems/actionpack-4.1.6/lib/action_controller/metal/implicit_render.rb:10:in `default_render'
[bundle].../gems/actionpack-4.1.6/lib/action_controller/metal/implicit_render.rb:5:in `send_action'
[bundle].../gems/actionpack-4.1.6/lib/abstract_controller/base.rb:189:in `process_action'
[bundle].../gems/actionpack-4.1.6/lib/action_controller/metal/rendering.rb:10:in `process_action'
[bundle].../gems/actionpack-4.1.6/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
[bundle].../gems/activesupport-4.1.6/lib/active_support/callbacks.rb:113:in `call'
[bundle].../gems/activesupport-4.1.6/lib/active_support/callbacks.rb:113:in `call'
[bundle].../gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
[bundle].../gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
[bundle].../gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
[bundle].../gems/activesupport-4.1.6/lib/active_support/callbacks.rb:229:in `call'
[bundle].../gems/activesupport-4.1.6/lib/active_support/callbacks.rb:229:in `block in halting'
[bundle].../gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
[bundle].../gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
[bundle].../gems/activesupport-4.1.6/lib/active_support/callbacks.rb:86:in `call'
[bundle].../gems/activesupport-4.1.6/lib/active_support/callbacks.rb:86:in `run_callbacks'
[bundle].../gems/actionpack-4.1.6/lib/abstract_controller/callbacks.rb:19:in `process_action'
[bundle].../gems/actionpack-4.1.6/lib/action_controller/metal/rescue.rb:29:in `process_action'
[bundle].../gems/actionpack-4.1.6/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
[bundle].../gems/activesupport-4.1.6/lib/active_support/notifications.rb:159:in `block in instrument'
[bundle].../gems/activesupport-4.1.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-4.1.6/lib/active_support/notifications.rb:159:in `instrument'
[bundle].../gems/actionpack-4.1.6/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
[bundle].../gems/actionpack-4.1.6/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
[bundle].../gems/activerecord-4.1.6/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
[bundle].../gems/actionpack-4.1.6/lib/abstract_controller/base.rb:136:in `process'
[bundle].../gems/actionview-4.1.6/lib/action_view/rendering.rb:30:in `process'
[bundle].../gems/actionpack-4.1.6/lib/action_controller/metal.rb:196:in `dispatch'
[bundle].../gems/actionpack-4.1.6/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
[bundle].../gems/actionpack-4.1.6/lib/action_controller/metal.rb:232:in `block in action'
[bundle].../gems/actionpack-4.1.6/lib/action_dispatch/routing/route_set.rb:82:in `call'
[bundle].../gems/actionpack-4.1.6/lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
[bundle].../gems/actionpack-4.1.6/lib/action_dispatch/routing/route_set.rb:50:in `call'
[bundle].../gems/actionpack-4.1.6/lib/action_dispatch/journey/router.rb:73:in `block in call'
[bundle].../gems/actionpack-4.1.6/lib/action_dispatch/journey/router.rb:59:in `each'
[bundle].../gems/actionpack-4.1.6/lib/action_dispatch/journey/router.rb:59:in `call'
[bundle].../gems/actionpack-4.1.6/lib/action_dispatch/routing/route_set.rb:678:in `call'
[bundle].../gems/party_foul-1.5.5/lib/party_foul/middleware.rb:8:in `call'
[bundle].../gems/rack-1.5.2/lib/rack/etag.rb:23:in `call'
[bundle].../gems/rack-1.5.2/lib/rack/conditionalget.rb:25:in `call'
[bundle].../gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
[bundle].../gems/actionpack-4.1.6/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
[bundle].../gems/actionpack-4.1.6/lib/action_dispatch/middleware/flash.rb:254:in `call'
[bundle].../gems/rack-1.5.2/lib/rack/session/abstract/id.rb:225:in `context'
[bundle].../gems/rack-1.5.2/lib/rack/session/abstract/id.rb:220:in `call'
[bundle].../gems/actionpack-4.1.6/lib/action_dispatch/middleware/cookies.rb:560:in `call'
[bundle].../gems/activerecord-4.1.6/lib/active_record/query_cache.rb:36:in `call'
[bundle].../gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
[bundle].../gems/activerecord-4.1.6/lib/active_record/migration.rb:380:in `call'
[bundle].../gems/actionpack-4.1.6/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
[bundle].../gems/activesupport-4.1.6/lib/active_support/callbacks.rb:82:in `run_callbacks'
[bundle].../gems/actionpack-4.1.6/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
[bundle].../gems/actionpack-4.1.6/lib/action_dispatch/middleware/reloader.rb:73:in `call'
[bundle].../gems/actionpack-4.1.6/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
[bundle].../gems/actionpack-4.1.6/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
[bundle].../gems/actionpack-4.1.6/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
[bundle].../gems/railties-4.1.6/lib/rails/rack/logger.rb:38:in `call_app'
[bundle].../gems/railties-4.1.6/lib/rails/rack/logger.rb:20:in `block in call'
[bundle].../gems/activesupport-4.1.6/lib/active_support/tagged_logging.rb:68:in `block in tagged'
[bundle].../gems/activesupport-4.1.6/lib/active_support/tagged_logging.rb:26:in `tagged'
[bundle].../gems/activesupport-4.1.6/lib/active_support/tagged_logging.rb:68:in `tagged'
[bundle].../gems/railties-4.1.6/lib/rails/rack/logger.rb:20:in `call'
[bundle].../gems/actionpack-4.1.6/lib/action_dispatch/middleware/request_id.rb:21:in `call'
[bundle].../gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
[bundle].../gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'
[bundle].../gems/activesupport-4.1.6/lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
[bundle].../gems/rack-1.5.2/lib/rack/lock.rb:17:in `call'
[bundle].../gems/actionpack-4.1.6/lib/action_dispatch/middleware/static.rb:64:in `call'
[bundle].../gems/rack-1.5.2/lib/rack/sendfile.rb:112:in `call'
[bundle].../gems/railties-4.1.6/lib/rails/engine.rb:514:in `call'
[bundle].../gems/railties-4.1.6/lib/rails/application.rb:144:in `call'
[bundle].../gems/rack-1.5.2/lib/rack/lock.rb:17:in `call'
[bundle].../gems/rack-1.5.2/lib/rack/content_length.rb:14:in `call'
[bundle].../gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in `service'
/Users/dougmeyer1/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
/Users/dougmeyer1/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
/Users/dougmeyer1/.rvm/rubies/ruby-2.1.3/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'</pre>
Fingerprint: `73dec62cb58adfd51c60129f4d1dc3048be442d1`

**Comment by DouglasMeyer** [comment]
<table><tr><th>Occurred At</th><td>January 01, 2015 20:44:03 -0600</td></tr><tr><th>URL</th><td>[GET] http://localhost:3000/v2/bank_entries</td></tr><tr><th>Params</th><td><table><tr><th>action</th><td>index</td></tr><tr><th>controller</th><td>v2/bank_entries</td></tr></table></td></tr><tr><th>Session</th><td>#&lt;ActionDispatch::Request::Session:0x007fe0b4420648&gt;</td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/127.0.0.1&#39;&gt;127.0.0.1&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate, sdch</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by DouglasMeyer** [comment]
<table><tr><th>Occurred At</th><td>January 01, 2015 21:02:55 -0600</td></tr><tr><th>URL</th><td>[GET] http://ledger.herokuapp.com/v2/bank_entries</td></tr><tr><th>Params</th><td><table><tr><th>action</th><td>index</td></tr><tr><th>controller</th><td>v2/bank_entries</td></tr></table></td></tr><tr><th>Session</th><td>#&lt;ActionDispatch::Request::Session:0x007f472fffb568&gt;</td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/108.202.124.240&#39;&gt;108.202.124.240&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate, sdch</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by DouglasMeyer** [comment]
<table><tr><th>Occurred At</th><td>January 01, 2015 21:05:45 -0600</td></tr><tr><th>URL</th><td>[GET] http://ledger-willis.herokuapp.com/v2/bank_entries</td></tr><tr><th>Params</th><td><table><tr><th>action</th><td>index</td></tr><tr><th>controller</th><td>v2/bank_entries</td></tr></table></td></tr><tr><th>Session</th><td>#&lt;ActionDispatch::Request::Session:0x007fd43fc75ea0&gt;</td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/108.202.124.240&#39;&gt;108.202.124.240&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate, sdch</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by DouglasMeyer** [comment]
This is from the deprecated v2 portion of the app.
