### ISSUE TITLE
V3::BankImportsController#create (NoMethodError) "undefined method `scan' for nil:NilClass"

### ISSUE THREAD

**Issue by DouglasMeyer** [DouglasMeyer/ledger#14]
<table><tr><th>Exception</th><td>undefined method `scan&#39; for nil:NilClass</td></tr><tr><th>Last Occurrence</th><td>October 29, 2016 14:23:30 -0500</td></tr><tr><th>Count</th><td>5</td></tr></table>

## Stack Trace
<pre><a href='https://github.com/DouglasMeyer/ledger/blob/7d1192342cbe21ee7a546f58bedf83f48974dd43/lib/parse_statement.rb#L13'>[app].../lib/parse_statement.rb:13:in `parse'</a>
<a href='https://github.com/DouglasMeyer/ledger/blob/7d1192342cbe21ee7a546f58bedf83f48974dd43/lib/parse_statement.rb#L52'>[app].../lib/parse_statement.rb:52:in `run'</a>
<a href='https://github.com/DouglasMeyer/ledger/blob/7d1192342cbe21ee7a546f58bedf83f48974dd43/app/models/bank_import.rb#L5'>[app].../app/models/bank_import.rb:5:in `upload!'</a>
<a href='https://github.com/DouglasMeyer/ledger/blob/7d1192342cbe21ee7a546f58bedf83f48974dd43/app/controllers/v3/bank_imports_controller.rb#L4'>[app].../app/controllers/v3/bank_imports_controller.rb:4:in `create'</a>
[bundle].../gems/actionpack-4.2.4/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
[bundle].../gems/actionpack-4.2.4/lib/abstract_controller/base.rb:198:in `process_action'
[bundle].../gems/actionpack-4.2.4/lib/action_controller/metal/rendering.rb:10:in `process_action'
[bundle].../gems/actionpack-4.2.4/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
[bundle].../gems/activesupport-4.2.4/lib/active_support/callbacks.rb:117:in `call'
[bundle].../gems/activesupport-4.2.4/lib/active_support/callbacks.rb:117:in `call'
[bundle].../gems/activesupport-4.2.4/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
[bundle].../gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
[bundle].../gems/activesupport-4.2.4/lib/active_support/callbacks.rb:505:in `call'
[bundle].../gems/activesupport-4.2.4/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
[bundle].../gems/activesupport-4.2.4/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
[bundle].../gems/activesupport-4.2.4/lib/active_support/callbacks.rb:81:in `run_callbacks'
[bundle].../gems/actionpack-4.2.4/lib/abstract_controller/callbacks.rb:19:in `process_action'
[bundle].../gems/actionpack-4.2.4/lib/action_controller/metal/rescue.rb:29:in `process_action'
[bundle].../gems/actionpack-4.2.4/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
[bundle].../gems/activesupport-4.2.4/lib/active_support/notifications.rb:164:in `block in instrument'
[bundle].../gems/activesupport-4.2.4/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-4.2.4/lib/active_support/notifications.rb:164:in `instrument'
[bundle].../gems/actionpack-4.2.4/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
[bundle].../gems/actionpack-4.2.4/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
[bundle].../gems/activerecord-4.2.4/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
[bundle].../gems/actionpack-4.2.4/lib/abstract_controller/base.rb:137:in `process'
[bundle].../gems/actionview-4.2.4/lib/action_view/rendering.rb:30:in `process'
[bundle].../gems/actionpack-4.2.4/lib/action_controller/metal.rb:196:in `dispatch'
[bundle].../gems/actionpack-4.2.4/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
[bundle].../gems/actionpack-4.2.4/lib/action_controller/metal.rb:237:in `block in action'
[bundle].../gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:76:in `call'
[bundle].../gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
[bundle].../gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:45:in `serve'
[bundle].../gems/actionpack-4.2.4/lib/action_dispatch/journey/router.rb:43:in `block in serve'
[bundle].../gems/actionpack-4.2.4/lib/action_dispatch/journey/router.rb:30:in `each'
[bundle].../gems/actionpack-4.2.4/lib/action_dispatch/journey/router.rb:30:in `serve'
[bundle].../gems/actionpack-4.2.4/lib/action_dispatch/routing/route_set.rb:821:in `call'
[bundle].../gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186:in `call!'
[bundle].../gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'
[bundle].../gems/omniauth-1.2.2/lib/omniauth/strategy.rb:186:in `call!'
[bundle].../gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'
[bundle].../gems/omniauth-1.2.2/lib/omniauth/builder.rb:59:in `call'
[bundle].../gems/party_foul-1.5.5/lib/party_foul/middleware.rb:8:in `call'
[bundle].../gems/rack-livereload-0.3.16/lib/rack/livereload.rb:23:in `_call'
[bundle].../gems/rack-livereload-0.3.16/lib/rack/livereload.rb:14:in `call'
[bundle].../gems/rack-1.6.4/lib/rack/etag.rb:24:in `call'
[bundle].../gems/rack-1.6.4/lib/rack/conditionalget.rb:38:in `call'
[bundle].../gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
[bundle].../gems/actionpack-4.2.4/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
[bundle].../gems/actionpack-4.2.4/lib/action_dispatch/middleware/flash.rb:260:in `call'
[bundle].../gems/rack-1.6.4/lib/rack/session/abstract/id.rb:225:in `context'
[bundle].../gems/rack-1.6.4/lib/rack/session/abstract/id.rb:220:in `call'
[bundle].../gems/actionpack-4.2.4/lib/action_dispatch/middleware/cookies.rb:560:in `call'
[bundle].../gems/activerecord-4.2.4/lib/active_record/query_cache.rb:36:in `call'
[bundle].../gems/activerecord-4.2.4/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
[bundle].../gems/activerecord-4.2.4/lib/active_record/migration.rb:377:in `call'
[bundle].../gems/actionpack-4.2.4/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
[bundle].../gems/activesupport-4.2.4/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
[bundle].../gems/activesupport-4.2.4/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
[bundle].../gems/activesupport-4.2.4/lib/active_support/callbacks.rb:81:in `run_callbacks'
[bundle].../gems/actionpack-4.2.4/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
[bundle].../gems/actionpack-4.2.4/lib/action_dispatch/middleware/reloader.rb:73:in `call'
[bundle].../gems/actionpack-4.2.4/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
[bundle].../gems/actionpack-4.2.4/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
[bundle].../gems/actionpack-4.2.4/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
[bundle].../gems/railties-4.2.4/lib/rails/rack/logger.rb:38:in `call_app'
[bundle].../gems/railties-4.2.4/lib/rails/rack/logger.rb:20:in `block in call'
[bundle].../gems/activesupport-4.2.4/lib/active_support/tagged_logging.rb:68:in `block in tagged'
[bundle].../gems/activesupport-4.2.4/lib/active_support/tagged_logging.rb:26:in `tagged'
[bundle].../gems/activesupport-4.2.4/lib/active_support/tagged_logging.rb:68:in `tagged'
[bundle].../gems/railties-4.2.4/lib/rails/rack/logger.rb:20:in `call'
[bundle].../gems/actionpack-4.2.4/lib/action_dispatch/middleware/request_id.rb:21:in `call'
[bundle].../gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
[bundle].../gems/rack-1.6.4/lib/rack/runtime.rb:18:in `call'
[bundle].../gems/activesupport-4.2.4/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
[bundle].../gems/rack-1.6.4/lib/rack/lock.rb:17:in `call'
[bundle].../gems/actionpack-4.2.4/lib/action_dispatch/middleware/static.rb:116:in `call'
[bundle].../gems/rack-1.6.4/lib/rack/sendfile.rb:113:in `call'
[bundle].../gems/railties-4.2.4/lib/rails/engine.rb:518:in `call'
[bundle].../gems/railties-4.2.4/lib/rails/application.rb:165:in `call'
[bundle].../gems/rack-1.6.4/lib/rack/lock.rb:17:in `call'
[bundle].../gems/rack-1.6.4/lib/rack/content_length.rb:15:in `call'
[bundle].../gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
/Users/douglas/.rbenv/versions/2.1.3/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'
/Users/douglas/.rbenv/versions/2.1.3/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'
/Users/douglas/.rbenv/versions/2.1.3/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'</pre>
Fingerprint: `88ba55dfd752dc1d3764bfa19ba9cf706fe605bc`

**Comment by DouglasMeyer** [comment]
Just testing PartyFoul by uploading some random file to the importer.

**Comment by DouglasMeyer** [comment]
Again, testing PartyFoul by uploading some random file to the importer.
