### ISSUE TITLE
V3::BankImportsController#create (NoMethodError) "undefined method `compact' for nil:NilClass"

### ISSUE THREAD

**Issue by DouglasMeyer** [DouglasMeyer/ledger#2]
<table><tr><th>Exception</th><td>undefined method `compact&#39; for nil:NilClass</td></tr><tr><th>Last Occurrence</th><td>January 16, 2015 14:31:20 -0600</td></tr><tr><th>Count</th><td>13</td></tr></table>

## Stack Trace
<pre><a href='https://github.com/DouglasMeyer/ledger/blob/a27ef38169ab02b0f6f7ba7bcc746c5b910d6ee2/app/models/bank_import.rb#L9'>[app].../app/models/bank_import.rb:9:in `block in upload!'</a>
[bundle].../gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `block in transaction'
[bundle].../gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract/database_statements.rb:209:in `within_new_transaction'
[bundle].../gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract/database_statements.rb:201:in `transaction'
[bundle].../gems/activerecord-4.1.6/lib/active_record/transactions.rb:208:in `transaction'
<a href='https://github.com/DouglasMeyer/ledger/blob/a27ef38169ab02b0f6f7ba7bcc746c5b910d6ee2/app/models/bank_import.rb#L8'>[app].../app/models/bank_import.rb:8:in `upload!'</a>
<a href='https://github.com/DouglasMeyer/ledger/blob/a27ef38169ab02b0f6f7ba7bcc746c5b910d6ee2/app/controllers/v3/bank_imports_controller.rb#L5'>[app].../app/controllers/v3/bank_imports_controller.rb:5:in `create'</a>
[bundle].../gems/actionpack-4.1.6/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
[bundle].../gems/actionpack-4.1.6/lib/abstract_controller/base.rb:189:in `process_action'
[bundle].../gems/actionpack-4.1.6/lib/action_controller/metal/rendering.rb:10:in `process_action'
[bundle].../gems/actionpack-4.1.6/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
[bundle].../gems/activesupport-4.1.6/lib/active_support/callbacks.rb:113:in `call'
[bundle].../gems/activesupport-4.1.6/lib/active_support/callbacks.rb:113:in `call'
[bundle].../gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
[bundle].../gems/activesupport-4.1.6/lib/active_support/callbacks.rb:229:in `call'
[bundle].../gems/activesupport-4.1.6/lib/active_support/callbacks.rb:229:in `block in halting'
[bundle].../gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `call'
[bundle].../gems/activesupport-4.1.6/lib/active_support/callbacks.rb:166:in `block in halting'
[bundle].../gems/activesupport-4.1.6/lib/active_support/callbacks.rb:86:in `call'
[bundle].../gems/activesupport-4.1.6/lib/active_support/callbacks.rb:86:in `run_callbacks'
[bundle].../gems/actionpack-4.1.6/lib/abstract_controller/callbacks.rb:19:in `process_action'
[bundle].../gems/actionpack-4.1.6/lib/action_controller/metal/rescue.rb:29:in `process_action'
[bundle].../gems/actionpack-4.1.6/lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
[bundle].../gems/activesupport-4.1.6/lib/active_support/notifications.rb:159:in `block in instrument'
[bundle].../gems/activesupport-4.1.6/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-4.1.6/lib/active_support/notifications.rb:159:in `instrument'
[bundle].../gems/actionpack-4.1.6/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
[bundle].../gems/actionpack-4.1.6/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
[bundle].../gems/activerecord-4.1.6/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
[bundle].../gems/actionpack-4.1.6/lib/abstract_controller/base.rb:136:in `process'
[bundle].../gems/actionview-4.1.6/lib/action_view/rendering.rb:30:in `process'
[bundle].../gems/actionpack-4.1.6/lib/action_controller/metal.rb:196:in `dispatch'
[bundle].../gems/actionpack-4.1.6/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
[bundle].../gems/actionpack-4.1.6/lib/action_controller/metal.rb:232:in `block in action'
[bundle].../gems/actionpack-4.1.6/lib/action_dispatch/routing/route_set.rb:82:in `call'
[bundle].../gems/actionpack-4.1.6/lib/action_dispatch/routing/route_set.rb:82:in `dispatch'
[bundle].../gems/actionpack-4.1.6/lib/action_dispatch/routing/route_set.rb:50:in `call'
[bundle].../gems/actionpack-4.1.6/lib/action_dispatch/journey/router.rb:73:in `block in call'
[bundle].../gems/actionpack-4.1.6/lib/action_dispatch/journey/router.rb:59:in `each'
[bundle].../gems/actionpack-4.1.6/lib/action_dispatch/journey/router.rb:59:in `call'
[bundle].../gems/actionpack-4.1.6/lib/action_dispatch/routing/route_set.rb:678:in `call'
[bundle].../gems/party_foul-1.5.5/lib/party_foul/middleware.rb:8:in `call'
[bundle].../gems/rack-1.5.2/lib/rack/etag.rb:23:in `call'
[bundle].../gems/rack-1.5.2/lib/rack/conditionalget.rb:35:in `call'
[bundle].../gems/rack-1.5.2/lib/rack/head.rb:11:in `call'
[bundle].../gems/actionpack-4.1.6/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
[bundle].../gems/actionpack-4.1.6/lib/action_dispatch/middleware/flash.rb:254:in `call'
[bundle].../gems/rack-1.5.2/lib/rack/session/abstract/id.rb:225:in `context'
[bundle].../gems/rack-1.5.2/lib/rack/session/abstract/id.rb:220:in `call'
[bundle].../gems/actionpack-4.1.6/lib/action_dispatch/middleware/cookies.rb:560:in `call'
[bundle].../gems/activerecord-4.1.6/lib/active_record/query_cache.rb:36:in `call'
[bundle].../gems/activerecord-4.1.6/lib/active_record/connection_adapters/abstract/connection_pool.rb:621:in `call'
[bundle].../gems/actionpack-4.1.6/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
[bundle].../gems/activesupport-4.1.6/lib/active_support/callbacks.rb:82:in `run_callbacks'
[bundle].../gems/actionpack-4.1.6/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
[bundle].../gems/actionpack-4.1.6/lib/action_dispatch/middleware/remote_ip.rb:76:in `call'
[bundle].../gems/actionpack-4.1.6/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
[bundle].../gems/actionpack-4.1.6/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
[bundle].../gems/railties-4.1.6/lib/rails/rack/logger.rb:38:in `call_app'
[bundle].../gems/railties-4.1.6/lib/rails/rack/logger.rb:20:in `block in call'
[bundle].../gems/activesupport-4.1.6/lib/active_support/tagged_logging.rb:68:in `block in tagged'
[bundle].../gems/activesupport-4.1.6/lib/active_support/tagged_logging.rb:26:in `tagged'
[bundle].../gems/activesupport-4.1.6/lib/active_support/tagged_logging.rb:68:in `tagged'
[bundle].../gems/railties-4.1.6/lib/rails/rack/logger.rb:20:in `call'
[bundle].../gems/actionpack-4.1.6/lib/action_dispatch/middleware/request_id.rb:21:in `call'
[bundle].../gems/rack-1.5.2/lib/rack/methodoverride.rb:21:in `call'
[bundle].../gems/rack-1.5.2/lib/rack/runtime.rb:17:in `call'
[bundle].../gems/activesupport-4.1.6/lib/active_support/cache/strategy/local_cache_middleware.rb:26:in `call'
[bundle].../gems/rack-1.5.2/lib/rack/sendfile.rb:112:in `call'
[bundle].../gems/sentry-raven-0.12.2/lib/raven/integrations/rack.rb:61:in `call'
[bundle].../gems/railties-4.1.6/lib/rails/engine.rb:514:in `call'
[bundle].../gems/railties-4.1.6/lib/rails/application.rb:144:in `call'
[bundle].../gems/rack-1.5.2/lib/rack/lock.rb:17:in `call'
[bundle].../gems/rack-1.5.2/lib/rack/content_length.rb:14:in `call'
[bundle].../gems/rack-1.5.2/lib/rack/handler/webrick.rb:60:in `service'
<a href='https://github.com/DouglasMeyer/ledger/blob/a27ef38169ab02b0f6f7ba7bcc746c5b910d6ee2/vendor/ruby-2.1.3/lib/ruby/2.1.0/webrick/httpserver.rb#L138'>[app].../vendor/ruby-2.1.3/lib/ruby/2.1.0/webrick/httpserver.rb:138:in `service'</a>
<a href='https://github.com/DouglasMeyer/ledger/blob/a27ef38169ab02b0f6f7ba7bcc746c5b910d6ee2/vendor/ruby-2.1.3/lib/ruby/2.1.0/webrick/httpserver.rb#L94'>[app].../vendor/ruby-2.1.3/lib/ruby/2.1.0/webrick/httpserver.rb:94:in `run'</a>
<a href='https://github.com/DouglasMeyer/ledger/blob/a27ef38169ab02b0f6f7ba7bcc746c5b910d6ee2/vendor/ruby-2.1.3/lib/ruby/2.1.0/webrick/server.rb#L295'>[app].../vendor/ruby-2.1.3/lib/ruby/2.1.0/webrick/server.rb:295:in `block in start_thread'</a></pre>
Fingerprint: `cda5d210387cff80ed1d27e76bf97a3c07512a3a`

**Comment by DouglasMeyer** [comment]
<table><tr><th>Occurred At</th><td>January 03, 2015 15:10:56 -0600</td></tr><tr><th>URL</th><td>[POST] http://ledger-willis.herokuapp.com/v3/bank_imports</td></tr><tr><th>Params</th><td><table><tr><th>utf8</th><td>✓</td></tr><tr><th>authenticity_token</th><td>sWwL1EWgbSc+48X7bfu5a7ZDpSDs+CTJkSuGzJ4ooh8=</td></tr><tr><th>upload</th><td>#&lt;ActionDispatch::Http::UploadedFile:0x007f111bbdd138&gt;</td></tr><tr><th>action</th><td>create</td></tr><tr><th>controller</th><td>v3/bank_imports</td></tr></table></td></tr><tr><th>Session</th><td>#&lt;ActionDispatch::Request::Session:0x007f111c5c9138&gt;</td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/66.140.176.88&#39;&gt;66.140.176.88&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (X11; CrOS armv7l 6310.68.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.96 Safari/537.36</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by DouglasMeyer** [comment]
<table><tr><th>Occurred At</th><td>January 05, 2015 19:05:05 -0600</td></tr><tr><th>URL</th><td>[POST] http://ledger-willis.herokuapp.com/v3/bank_imports</td></tr><tr><th>Params</th><td><table><tr><th>utf8</th><td>✓</td></tr><tr><th>authenticity_token</th><td>sWwL1EWgbSc+48X7bfu5a7ZDpSDs+CTJkSuGzJ4ooh8=</td></tr><tr><th>upload</th><td>#&lt;ActionDispatch::Http::UploadedFile:0x007f542f029b00&gt;</td></tr><tr><th>action</th><td>create</td></tr><tr><th>controller</th><td>v3/bank_imports</td></tr></table></td></tr><tr><th>Session</th><td>#&lt;ActionDispatch::Request::Session:0x007f542ecb9a10&gt;</td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/66.140.176.88&#39;&gt;66.140.176.88&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (X11; CrOS armv7l 6310.68.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.96 Safari/537.36</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by DouglasMeyer** [comment]
<table><tr><th>Occurred At</th><td>January 05, 2015 19:10:47 -0600</td></tr><tr><th>URL</th><td>[POST] http://ledger-willis.herokuapp.com/v3/bank_imports</td></tr><tr><th>Params</th><td><table><tr><th>utf8</th><td>✓</td></tr><tr><th>authenticity_token</th><td>sWwL1EWgbSc+48X7bfu5a7ZDpSDs+CTJkSuGzJ4ooh8=</td></tr><tr><th>upload</th><td>#&lt;ActionDispatch::Http::UploadedFile:0x007f542f0da888&gt;</td></tr><tr><th>action</th><td>create</td></tr><tr><th>controller</th><td>v3/bank_imports</td></tr></table></td></tr><tr><th>Session</th><td>#&lt;ActionDispatch::Request::Session:0x007f542ed98e18&gt;</td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/66.140.176.88&#39;&gt;66.140.176.88&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (X11; CrOS armv7l 6310.68.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.96 Safari/537.36</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by DouglasMeyer** [comment]
<table><tr><th>Occurred At</th><td>January 05, 2015 19:15:08 -0600</td></tr><tr><th>URL</th><td>[POST] http://ledger-willis.herokuapp.com/v3/bank_imports</td></tr><tr><th>Params</th><td><table><tr><th>utf8</th><td>✓</td></tr><tr><th>authenticity_token</th><td>sWwL1EWgbSc+48X7bfu5a7ZDpSDs+CTJkSuGzJ4ooh8=</td></tr><tr><th>upload</th><td>#&lt;ActionDispatch::Http::UploadedFile:0x007f542dfdf358&gt;</td></tr><tr><th>action</th><td>create</td></tr><tr><th>controller</th><td>v3/bank_imports</td></tr></table></td></tr><tr><th>Session</th><td>#&lt;ActionDispatch::Request::Session:0x007f542d06a968&gt;</td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/66.140.176.88&#39;&gt;66.140.176.88&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (X11; CrOS armv7l 6310.68.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.96 Safari/537.36</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by DouglasMeyer** [comment]
<table><tr><th>Occurred At</th><td>January 05, 2015 19:40:24 -0600</td></tr><tr><th>URL</th><td>[POST] http://ledger-willis.herokuapp.com/v3/bank_imports</td></tr><tr><th>Params</th><td><table><tr><th>utf8</th><td>✓</td></tr><tr><th>authenticity_token</th><td>sWwL1EWgbSc+48X7bfu5a7ZDpSDs+CTJkSuGzJ4ooh8=</td></tr><tr><th>upload</th><td>#&lt;ActionDispatch::Http::UploadedFile:0x007f5409898320&gt;</td></tr><tr><th>action</th><td>create</td></tr><tr><th>controller</th><td>v3/bank_imports</td></tr></table></td></tr><tr><th>Session</th><td>#&lt;ActionDispatch::Request::Session:0x007f54097c8f08&gt;</td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/66.140.176.88&#39;&gt;66.140.176.88&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (X11; CrOS armv7l 6310.68.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.96 Safari/537.36</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by DouglasMeyer** [comment]
<table><tr><th>Occurred At</th><td>January 05, 2015 19:44:21 -0600</td></tr><tr><th>URL</th><td>[POST] http://ledger-willis.herokuapp.com/v3/bank_imports</td></tr><tr><th>Params</th><td><table><tr><th>utf8</th><td>✓</td></tr><tr><th>authenticity_token</th><td>sWwL1EWgbSc+48X7bfu5a7ZDpSDs+CTJkSuGzJ4ooh8=</td></tr><tr><th>upload</th><td>#&lt;ActionDispatch::Http::UploadedFile:0x007f5408e6d2b0&gt;</td></tr><tr><th>action</th><td>create</td></tr><tr><th>controller</th><td>v3/bank_imports</td></tr></table></td></tr><tr><th>Session</th><td>#&lt;ActionDispatch::Request::Session:0x007f5408f0e200&gt;</td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/66.140.176.88&#39;&gt;66.140.176.88&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (X11; CrOS armv7l 6310.68.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.96 Safari/537.36</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by DouglasMeyer** [comment]
<table><tr><th>Occurred At</th><td>January 09, 2015 14:51:50 -0600</td></tr><tr><th>URL</th><td>[POST] http://ledger-willis.herokuapp.com/v3/bank_imports</td></tr><tr><th>Params</th><td><table><tr><th>utf8</th><td>✓</td></tr><tr><th>authenticity_token</th><td>sWwL1EWgbSc+48X7bfu5a7ZDpSDs+CTJkSuGzJ4ooh8=</td></tr><tr><th>upload</th><td>#&lt;ActionDispatch::Http::UploadedFile:0x007f9bd79ae780&gt;</td></tr><tr><th>action</th><td>create</td></tr><tr><th>controller</th><td>v3/bank_imports</td></tr></table></td></tr><tr><th>Session</th><td>#&lt;ActionDispatch::Request::Session:0x007f9bd74b9c70&gt;</td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/66.140.176.88&#39;&gt;66.140.176.88&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (X11; CrOS armv7l 6310.68.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.96 Safari/537.36</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by DouglasMeyer** [comment]
<table><tr><th>Occurred At</th><td>January 09, 2015 15:02:13 -0600</td></tr><tr><th>URL</th><td>[POST] http://ledger-willis.herokuapp.com/v3/bank_imports</td></tr><tr><th>Params</th><td><table><tr><th>utf8</th><td>✓</td></tr><tr><th>authenticity_token</th><td>sWwL1EWgbSc+48X7bfu5a7ZDpSDs+CTJkSuGzJ4ooh8=</td></tr><tr><th>upload</th><td>#&lt;ActionDispatch::Http::UploadedFile:0x007f9bb18460f8&gt;</td></tr><tr><th>action</th><td>create</td></tr><tr><th>controller</th><td>v3/bank_imports</td></tr></table></td></tr><tr><th>Session</th><td>#&lt;ActionDispatch::Request::Session:0x007f9bb1a52f68&gt;</td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/66.140.176.88&#39;&gt;66.140.176.88&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (X11; CrOS armv7l 6310.68.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.96 Safari/537.36</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by DouglasMeyer** [comment]
<table><tr><th>Occurred At</th><td>January 10, 2015 20:41:33 -0600</td></tr><tr><th>URL</th><td>[POST] http://ledger-willis.herokuapp.com/v3/bank_imports</td></tr><tr><th>Params</th><td><table><tr><th>utf8</th><td>✓</td></tr><tr><th>authenticity_token</th><td>sWwL1EWgbSc+48X7bfu5a7ZDpSDs+CTJkSuGzJ4ooh8=</td></tr><tr><th>upload</th><td>#&lt;ActionDispatch::Http::UploadedFile:0x007f63ec1f1ee8&gt;</td></tr><tr><th>action</th><td>create</td></tr><tr><th>controller</th><td>v3/bank_imports</td></tr></table></td></tr><tr><th>Session</th><td>#&lt;ActionDispatch::Request::Session:0x007f63ef46aac8&gt;</td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/66.140.176.88&#39;&gt;66.140.176.88&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (X11; CrOS armv7l 6310.68.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.96 Safari/537.36</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by DouglasMeyer** [comment]
<table><tr><th>Occurred At</th><td>January 10, 2015 20:43:48 -0600</td></tr><tr><th>URL</th><td>[POST] http://ledger-willis.herokuapp.com/v3/bank_imports</td></tr><tr><th>Params</th><td><table><tr><th>utf8</th><td>✓</td></tr><tr><th>authenticity_token</th><td>sWwL1EWgbSc+48X7bfu5a7ZDpSDs+CTJkSuGzJ4ooh8=</td></tr><tr><th>upload</th><td>#&lt;ActionDispatch::Http::UploadedFile:0x007f63ee2fa130&gt;</td></tr><tr><th>action</th><td>create</td></tr><tr><th>controller</th><td>v3/bank_imports</td></tr></table></td></tr><tr><th>Session</th><td>#&lt;ActionDispatch::Request::Session:0x007f63ecfb5b88&gt;</td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/66.140.176.88&#39;&gt;66.140.176.88&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (X11; CrOS armv7l 6310.68.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.96 Safari/537.36</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by DouglasMeyer** [comment]
<table><tr><th>Occurred At</th><td>January 10, 2015 21:04:03 -0600</td></tr><tr><th>URL</th><td>[POST] http://ledger-willis.herokuapp.com/v3/bank_imports</td></tr><tr><th>Params</th><td><table><tr><th>utf8</th><td>✓</td></tr><tr><th>authenticity_token</th><td>sWwL1EWgbSc+48X7bfu5a7ZDpSDs+CTJkSuGzJ4ooh8=</td></tr><tr><th>upload</th><td>#&lt;ActionDispatch::Http::UploadedFile:0x007f63ef27ca68&gt;</td></tr><tr><th>action</th><td>create</td></tr><tr><th>controller</th><td>v3/bank_imports</td></tr></table></td></tr><tr><th>Session</th><td>#&lt;ActionDispatch::Request::Session:0x007f63eec48020&gt;</td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/66.140.176.88&#39;&gt;66.140.176.88&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (X11; CrOS armv7l 6310.68.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.96 Safari/537.36</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by DouglasMeyer** [comment]
<table><tr><th>Occurred At</th><td>January 10, 2015 21:18:51 -0600</td></tr><tr><th>URL</th><td>[POST] http://ledger-willis.herokuapp.com/v3/bank_imports</td></tr><tr><th>Params</th><td><table><tr><th>utf8</th><td>✓</td></tr><tr><th>authenticity_token</th><td>sWwL1EWgbSc+48X7bfu5a7ZDpSDs+CTJkSuGzJ4ooh8=</td></tr><tr><th>upload</th><td>#&lt;ActionDispatch::Http::UploadedFile:0x007f63d0e368c8&gt;</td></tr><tr><th>action</th><td>create</td></tr><tr><th>controller</th><td>v3/bank_imports</td></tr></table></td></tr><tr><th>Session</th><td>#&lt;ActionDispatch::Request::Session:0x007f63d0f5f718&gt;</td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/66.140.176.88&#39;&gt;66.140.176.88&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (X11; CrOS armv7l 6310.68.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.96 Safari/537.36</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8</td></tr></table></td></tr></table>

**Comment by DouglasMeyer** [comment]
<table><tr><th>Occurred At</th><td>January 16, 2015 14:31:20 -0600</td></tr><tr><th>URL</th><td>[POST] http://ledger.herokuapp.com/v3/bank_imports</td></tr><tr><th>Params</th><td><table><tr><th>utf8</th><td>✓</td></tr><tr><th>authenticity_token</th><td>amTrUINue8b3LMj/btD1ffk6jOe72OAOV7W/PHwAtZM=</td></tr><tr><th>upload</th><td>#&lt;ActionDispatch::Http::UploadedFile:0x007f5a00c7dbf0&gt;</td></tr><tr><th>action</th><td>create</td></tr><tr><th>controller</th><td>v3/bank_imports</td></tr></table></td></tr><tr><th>Session</th><td>#&lt;ActionDispatch::Request::Session:0x007f5a006e6d18&gt;</td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/108.202.124.240&#39;&gt;108.202.124.240&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_1) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.95 Safari/537.36</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8</td></tr></table></td></tr></table>
