### ISSUE TITLE
ApiController#bulk (UncaughtThrowError) "uncaught throw :abort"

### ISSUE THREAD

**Issue by DouglasMeyer** [DouglasMeyer/ledger#22]
<table><tr><th>Exception</th><td>uncaught throw :abort</td></tr><tr><th>Last Occurrence</th><td>October 22, 2016 12:55:26 -0500</td></tr><tr><th>Count</th><td>1</td></tr></table>

## Stack Trace
<pre><a href='https://github.com/DouglasMeyer/ledger/blob/52abcd767dbe70f20e2c875e29bff262762d2cf1/app/controllers/application_controller.rb#L12'>[app].../app/controllers/application_controller.rb:12:in `throw'</a>
<a href='https://github.com/DouglasMeyer/ledger/blob/52abcd767dbe70f20e2c875e29bff262762d2cf1/app/controllers/application_controller.rb#L12'>[app].../app/controllers/application_controller.rb:12:in `authenticate'</a>
[bundle].../gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:382:in `block in make_lambda'
[bundle].../gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:169:in `block (2 levels) in halting'
[bundle].../gems/actionpack-5.0.0.1/lib/abstract_controller/callbacks.rb:12:in `block (2 levels) in <module:Callbacks>'
[bundle].../gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:170:in `block in halting'
[bundle].../gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:454:in `block in call'
[bundle].../gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:454:in `each'
[bundle].../gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:454:in `call'
[bundle].../gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
[bundle].../gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
[bundle].../gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:90:in `run_callbacks'
[bundle].../gems/actionpack-5.0.0.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
[bundle].../gems/actionpack-5.0.0.1/lib/action_controller/metal/rescue.rb:20:in `process_action'
[bundle].../gems/actionpack-5.0.0.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
[bundle].../gems/activesupport-5.0.0.1/lib/active_support/notifications.rb:164:in `block in instrument'
[bundle].../gems/activesupport-5.0.0.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
[bundle].../gems/activesupport-5.0.0.1/lib/active_support/notifications.rb:164:in `instrument'
[bundle].../gems/actionpack-5.0.0.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
[bundle].../gems/actionpack-5.0.0.1/lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
[bundle].../gems/activerecord-5.0.0.1/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
[bundle].../gems/actionpack-5.0.0.1/lib/abstract_controller/base.rb:126:in `process'
[bundle].../gems/actionview-5.0.0.1/lib/action_view/rendering.rb:30:in `process'
[bundle].../gems/actionpack-5.0.0.1/lib/action_controller/metal.rb:190:in `dispatch'
[bundle].../gems/actionpack-5.0.0.1/lib/action_controller/metal.rb:262:in `dispatch'
[bundle].../gems/actionpack-5.0.0.1/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
[bundle].../gems/actionpack-5.0.0.1/lib/action_dispatch/routing/route_set.rb:32:in `serve'
[bundle].../gems/actionpack-5.0.0.1/lib/action_dispatch/journey/router.rb:39:in `block in serve'
[bundle].../gems/actionpack-5.0.0.1/lib/action_dispatch/journey/router.rb:26:in `each'
[bundle].../gems/actionpack-5.0.0.1/lib/action_dispatch/journey/router.rb:26:in `serve'
[bundle].../gems/actionpack-5.0.0.1/lib/action_dispatch/routing/route_set.rb:725:in `call'
[bundle].../gems/omniauth-1.3.1/lib/omniauth/strategy.rb:186:in `call!'
[bundle].../gems/omniauth-1.3.1/lib/omniauth/strategy.rb:164:in `call'
[bundle].../gems/omniauth-1.3.1/lib/omniauth/builder.rb:63:in `call'
[bundle].../gems/party_foul-1.5.5/lib/party_foul/middleware.rb:8:in `call'
[bundle].../gems/rack-2.0.1/lib/rack/etag.rb:25:in `call'
[bundle].../gems/rack-2.0.1/lib/rack/conditional_get.rb:38:in `call'
[bundle].../gems/rack-2.0.1/lib/rack/head.rb:12:in `call'
[bundle].../gems/rack-2.0.1/lib/rack/session/abstract/id.rb:222:in `context'
[bundle].../gems/rack-2.0.1/lib/rack/session/abstract/id.rb:216:in `call'
[bundle].../gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/cookies.rb:613:in `call'
[bundle].../gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
[bundle].../gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:97:in `__run_callbacks__'
[bundle].../gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
[bundle].../gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:90:in `run_callbacks'
[bundle].../gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/callbacks.rb:36:in `call'
[bundle].../gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
[bundle].../gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
[bundle].../gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
[bundle].../gems/railties-5.0.0.1/lib/rails/rack/logger.rb:36:in `call_app'
[bundle].../gems/railties-5.0.0.1/lib/rails/rack/logger.rb:24:in `block in call'
[bundle].../gems/activesupport-5.0.0.1/lib/active_support/tagged_logging.rb:70:in `block in tagged'
[bundle].../gems/activesupport-5.0.0.1/lib/active_support/tagged_logging.rb:26:in `tagged'
[bundle].../gems/activesupport-5.0.0.1/lib/active_support/tagged_logging.rb:70:in `tagged'
[bundle].../gems/railties-5.0.0.1/lib/rails/rack/logger.rb:24:in `call'
[bundle].../gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/request_id.rb:24:in `call'
[bundle].../gems/rack-2.0.1/lib/rack/method_override.rb:22:in `call'
[bundle].../gems/rack-2.0.1/lib/rack/runtime.rb:22:in `call'
[bundle].../gems/activesupport-5.0.0.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
[bundle].../gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/executor.rb:12:in `call'
[bundle].../gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/static.rb:136:in `call'
[bundle].../gems/rack-2.0.1/lib/rack/sendfile.rb:111:in `call'
[bundle].../gems/railties-5.0.0.1/lib/rails/engine.rb:522:in `call'
[bundle].../gems/rack-2.0.1/lib/rack/handler/webrick.rb:86:in `service'
<a href='https://github.com/DouglasMeyer/ledger/blob/52abcd767dbe70f20e2c875e29bff262762d2cf1/vendor/ruby-2.3.1/lib/ruby/2.3.0/webrick/httpserver.rb#L140'>[app].../vendor/ruby-2.3.1/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'</a>
<a href='https://github.com/DouglasMeyer/ledger/blob/52abcd767dbe70f20e2c875e29bff262762d2cf1/vendor/ruby-2.3.1/lib/ruby/2.3.0/webrick/httpserver.rb#L96'>[app].../vendor/ruby-2.3.1/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'</a>
<a href='https://github.com/DouglasMeyer/ledger/blob/52abcd767dbe70f20e2c875e29bff262762d2cf1/vendor/ruby-2.3.1/lib/ruby/2.3.0/webrick/server.rb#L296'>[app].../vendor/ruby-2.3.1/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'</a></pre>
Fingerprint: `fbcd400a5e69ecb0dc58ace30374fd34f27eb20c`

**Comment by DouglasMeyer** [comment]
<table><tr><th>Occurred At</th><td>October 22, 2016 12:55:26 -0500</td></tr><tr><th>URL</th><td>[POST] http://ledger.herokuapp.com/api</td></tr><tr><th>Params</th><td><table><tr><th>_json</th><td>[{&quot;resource&quot;=&gt;&quot;Account_v1&quot;, &quot;action&quot;=&gt;&quot;read&quot;, &quot;reference&quot;=&gt;5}, {&quot;resource&quot;=&gt;&quot;BankEntry_v1&quot;, &quot;action&quot;=&gt;&quot;read&quot;, &quot;reference&quot;=&gt;6}, {&quot;resource&quot;=&gt;&quot;ProjectedEntry_v1&quot;, &quot;action&quot;=&gt;&quot;read&quot;, &quot;reference&quot;=&gt;7}, {&quot;needsDistribution&quot;=&gt;true, &quot;resource&quot;=&gt;&quot;BankEntry_v1&quot;, &quot;action&quot;=&gt;&quot;read&quot;, &quot;reference&quot;=&gt;8}, {&quot;resource&quot;=&gt;&quot;LedgerSummary_v1&quot;, &quot;action&quot;=&gt;&quot;read&quot;, &quot;reference&quot;=&gt;9}]</td></tr><tr><th>controller</th><td>api</td></tr><tr><th>action</th><td>bulk</td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/173.30.186.247&#39;&gt;173.30.186.247&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_6) AppleWebKit/601.7.8 (KHTML, like Gecko) Version/9.1.3 Safari/601.7.8</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>application/json, text/plain, */*</td></tr></table></td></tr></table>

**Comment by DouglasMeyer** [comment]
Fixed with be78b4e4bb990949b248b8f00a7b817710c65564
